version: '3'
services:
  db:
    container_name: db
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
    networks:
      - backend
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /var/www/node_modules
      - .:/var/www
    environment:
      NODE_ENV: dev
    depends_on:
      - db
    networks:
      - backend
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: .
      dockerfile: ./docker/dev/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend
networks:
  backend: